### PR TITLE
Remove random_direction() in favor of action_space.sample()

### PR DESCRIPTION
**Pull request by nickjalbert**
Made the change suggested in Issue https://github.com/nickjalbert/improved-funicular/issues/18

Would it make sense to consolidate our different 2048 environments into the-one-environment-to-rule-them-all?

### CODE REVIEW

**Comment by andyk** [comment]
Yeah, we can just remove the one I wrote, and rename yours.

**Comment by andyk** [comment]
LGTM though not sure what is causing the merge conflict. I've been pushing things that are in contrib to your repo without PRs since they don't touch core logic. Would you prefer that we always use PRs to commit to nickjalbert/master and I only push my WIP code to my fork or branches?

**Comment by nickjalbert** [comment]
> LGTM though not sure what is causing the merge conflict.

Ah, I had fixed a lint complaint in one of the `contrib/` files that you had already fixed in master.  Just resolved the conflict!

> Would you prefer that we always use PRs to commit to nickjalbert/master and I only push my WIP code to my fork or branches?

Seems unnecessary to always use PRs, especially if not working on the core stuff.  I propose that we should generally feel free to push to master whenever, but use PRs for highlighting code of general interest and/or getting feedback.  

I also propose that we try to keep the master build as green as possible; so I think either of us should feel free to push updates to master if/when any lint or test complaints sneak in.

**Comment by andyk** [comment]
> > LGTM though not sure what is causing the merge conflict.
> 
> Ah, I had fixed a lint complaint in one of the `contrib/` files that you had already fixed in master. Just resolved the conflict!
> 
> > Would you prefer that we always use PRs to commit to nickjalbert/master and I only push my WIP code to my fork or branches?
> 
> Seems unnecessary to always use PRs, especially if not working on the core stuff. I propose that we should generally feel free to push to master whenever, but use PRs for highlighting code of general interest and/or getting feedback.
> 
> I also propose that we try to keep the master build as green as possible; so I think either of us should feel free to push updates to master if/when any lint or test complaints sneak in.

This sounds like a great process!

**Pull request merged**
